apiVersion: v1
kind: ConfigMap
metadata:
  name: cancer-config
data:
  MODEL_PATH: /app/artifacts/model.joblib
  MODEL_NAME: cancer-classifier
  MLFLOW_TRACKING_URI: http://mlflow:5000
  LOG_LEVEL: INFO